In [1]:
import numpy as np

a = np.array([2,4,5,8,10])
print(a)

[ 2  4  5  8 10]


In [2]:
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
p = np.zeros((3,3))
print(p)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
s = np.eye(4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
q = np.ones((3,3))
print(q)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
r = np.full((2,2),4)
print(r)

[[4 4]
 [4 4]]


In [7]:
s = np.random.random((3,1))
print(s)

[[0.79793338]
 [0.32868768]
 [0.1786074 ]]


In [8]:
t=np.random.random((3,3,))
print(t)

[[0.47442594 0.13410858 0.41297695]
 [0.62696338 0.15095737 0.50182648]
 [0.68105161 0.36614293 0.50043521]]


In [9]:
print(type(a),"...",a.shape,"...",a.dtype)
print(type(b),"...",b.shape,"...",b.dtype)
print(type(p),"...",p.shape,"...",p.dtype)
print(type(q),"...",q.shape,"...",q.dtype)
print(type(r),"...",r.shape,"...",r.dtype)
print(type(s),"...",s.shape,"...",s.dtype)
print(type(t),"...",t.shape,"...",t.dtype)

<class 'numpy.ndarray'> ... (5,) ... int64
<class 'numpy.ndarray'> ... (10,) ... int64
<class 'numpy.ndarray'> ... (3, 3) ... float64
<class 'numpy.ndarray'> ... (3, 3) ... float64
<class 'numpy.ndarray'> ... (2, 2) ... int64
<class 'numpy.ndarray'> ... (3, 1) ... float64
<class 'numpy.ndarray'> ... (3, 3) ... float64


In [10]:
z = np.array([2,4,6,8,10])
print(z)

[ 2  4  6  8 10]


In [11]:
print(type(z),"...",z.shape,"...",z.dtype)

<class 'numpy.ndarray'> ... (5,) ... int64


In [12]:
flat_t =  t.flatten()
print(type(flat_t),"...",flat_t.shape,"...",flat_t.dtype)

<class 'numpy.ndarray'> ... (9,) ... float64


In [13]:
ravel_t = t.ravel()
print(type(ravel_t),"...",ravel_t.shape,"...",ravel_t.dtype)

<class 'numpy.ndarray'> ... (9,) ... float64


In [14]:
print(p)
print(q)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
hpq = np.hstack((p,q))
print(hpq)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [18]:
hpq = np.hstack((p,s))
print(hpq)

[[0.         0.         0.         0.79793338]
 [0.         0.         0.         0.32868768]
 [0.         0.         0.         0.1786074 ]]


In [19]:
hpq = np.concatenate((p,s),axis=1)
print(hpq)

[[0.         0.         0.         0.79793338]
 [0.         0.         0.         0.32868768]
 [0.         0.         0.         0.1786074 ]]


In [24]:
hpq = np.vstack((p,s.transpose()))
print(hpq)

[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.79793338 0.32868768 0.1786074 ]]


In [26]:
hpq = np.concatenate((p,s.transpose()),axis=0)
print(hpq)

[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.79793338 0.32868768 0.1786074 ]]


In [28]:
print(hpq.shape)


(4, 3)


In [29]:
hpq = np.dstack((p,q))
print(hpq)

[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]


In [30]:
print(hpq.shape)

(3, 3, 2)


In [31]:
print(hpq.tolist())

[[[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]], [[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]], [[0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]]
